package com.antriksh.app.pdf.utilities;

import java.io.FileOutputStream;
import java.io.IOException;
import java.net.MalformedURLException;
import java.text.SimpleDateFormat;
import java.util.Date;

import org.springframework.stereotype.Component;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;


@Component
public class PDFGenerator {

	private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18, Font.BOLD);
	private static Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.NORMAL, BaseColor.RED);
	private static Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16, Font.BOLD);
	private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD);

	 
	
	public void generatePDF(String filePath, String name, String emailId, String phone, String operatingAirlines,
			 String departureCity, String arrivalcity,Date departureDate) {
		try {
			Document document = new Document();
			PdfWriter.getInstance(document, new FileOutputStream(filePath));
			document.open();
			addMetaData(document);
			addTitleAndTable(document, name, emailId, phone, operatingAirlines,  departureCity,
					arrivalcity,departureDate);
			document.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public static void addMetaData(Document document) {
		document.addTitle("My first PDF");
		document.addSubject("Using iText");
		document.addKeywords("Java, PDF, iText");
		document.addAuthor("Lars Vogel");
		document.addCreator("Lars Vogel");
	}

	public static void addTitleAndTable(Document document, String name, String emailId, String phone,
			String operatingAirlines,  String departureCity, String arrivalcity,Date departureDate)
			throws DocumentException, MalformedURLException, IOException {
		Paragraph preface = new Paragraph();
		preface.add(new Paragraph("Flight Booking Details", catFont));
		preface.add(new Paragraph("Report generated by : " + "Flight Reservation company " + new Date(), smallBold));

		document.add(preface);
		document.add(Chunk.NEWLINE);
		// Creating an ImageData object       
	      String imFile = "C:\\Users\\Antriksh\\Desktop\\Ticket\\indigo-Image.png";       
	     // String imFile = "/static/images/indigo-Image.png";       
	      
	      // Creating an Image object        
	      Image image =  Image.getInstance(imFile);
	      image.scaleAbsolute(150f, 150f);
	      
	      // Adding image to the document       
	      document.add(image);   
		
		document.add(Chunk.NEWLINE);
		document.add(Chunk.NEWLINE);

		PdfPTable table = new PdfPTable(2);
		table.setWidthPercentage(100);

		PdfPCell c1 = new PdfPCell(new Phrase("Passenger name"));
		c1.setHorizontalAlignment(Element.ALIGN_CENTER);
		c1.setColspan(2);
		table.addCell(c1);

		table.addCell("Passenger name");
		table.addCell(name);
		table.addCell("Email Id");
		table.addCell(emailId);
		table.addCell("Phone number");
		table.addCell(phone);

		document.add(table);
		
		SimpleDateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");  
	    String strDate = formatter.format(departureDate); 

		PdfPTable table1 = new PdfPTable(2);
		table1.setWidthPercentage(100);

		PdfPCell c2 = new PdfPCell(new Phrase("Flight Details"));
		c2.setHorizontalAlignment(Element.ALIGN_CENTER);
		c2.setColspan(2);
		table1.addCell(c2);

		table1.addCell("Opearting Airlines");
		table1.addCell(operatingAirlines);
		table1.addCell("Departure City");
		table1.addCell(departureCity);
		table1.addCell("Arrival City");
		table1.addCell(arrivalcity);
		table1.addCell("Departure Date");
		table1.addCell(strDate);
		
		document.add(table1);
		
		document.add(Chunk.NEWLINE);
		document.add(Chunk.NEWLINE);
		document.add(Chunk.NEWLINE);
		document.add(Chunk.NEWLINE);
		preface.add(new Paragraph("This document describes something which is very important ", smallBold));
		//document.add(preface);

		preface.add(new Paragraph(
				"This document is a preliminary version and not subject to your license agreement or any other agreement with vogella.com ;-).",
				redFont));

		//document.add(preface);
		// Start a new page
		//document.newPage();
		document.add(preface);

		document.close();

	}
}
